const orderTypes ={
    SAVE_ORDER_HISTORY_START: 'SAVE_ORDER_HISTORY_START',
    GET_USER_ORDER_HISTORY: 'GET_USER_ORDER_HISTORY',
    SET_USER_ORDER_HISTORY: 'SET_USER_ORDER_HISTORY',
};

export default orderTypes;